### ISSUE TITLE
I need to add some data to this application

### ISSUE THREAD

**Issue by ericksonugs** [UGS-GIO/boreholeApp#16]
The link below is the updated spreadsheet for the database. Please replace all data with the data within the spreadsheet. 

Spreadsheet:
https://drive.google.com/file/d/1U_u1sgAzaPFWGlxSzrFEet0phw2iZ73a/view?usp=sharing

Once complete, this bug can be resolved:
https://github.com/UGS-GIO/boreholeApp/issues/13

**Comment by gordondouglass** [comment]
I updated the borehole data set with the new spreadsheet. It is a feature class in a geodatabase located here:

G:\Shared drives\UGS_Hazards_Geotech\Geotechnical Database

And is called Borehole_Data_20201119.gdb. It contains both the feature class of borehole locations as well as the two related tables.

**Comment by marshallrobinson** [comment]
Thanks @gordondouglass. @ericksonugs, did this data-update take care of what you were expecting it to do?

**Comment by ericksonugs** [comment]
@marshallrobinson The webapp has not yet been updated with the current database, when that reflects the update, this can be closed.

**Comment by gordondouglass** [comment]
I have updated the AGOL interactive web map app with the new data:

https://utahdnr.maps.arcgis.com/apps/webappviewer/index.html?id=728e69d57f174f5cbe4f601eafc29105

**Comment by ericksonugs** [comment]
Thanks @gordondouglass, that portal looks great! The UGS webportal app at https://geology.utah.gov/apps/borehole/ has yet to be updated. Once that portal is current, we can close this update thread and, after verification, issue https://github.com/UGS-GIO/boreholeApp/issues/13 can be resolved too.

**Comment by marshallrobinson** [comment]
Ok, thanks for the update @ericksonugs. @gordondouglass, was this published as a new service, or were new fields introduced, or did it overwrite the existing service that Lance's web application is using? Lance's application should have shown the updated information if the original service was overwritten.

**Comment by marthajensen** [comment]
@marshallrobinson the service for Lance's app hasn't been overwritten yet... working on that right now :)

**Comment by marthajensen** [comment]
@ericksonugs the new data should be in the app now

@lance-weaver there is a newly symbolized borehole type - "Cone Penetration test" - symbolized as a hot pink dot (same size as the Drill and Trench dots)

@gordondouglass - the new data had a few fields that differed ever so slightly from the original service (i.e. new underscores or underscores removed). The projection was also different. To make it easier in the future, I created a gdb with the web app schema here: "G:\Shared drives\UGS_Hazards_Geotech\Geotechnical Database\Borehole_Data_Web_Schema_WGS84.gdb" Next time, lets use that and append Ben's data into this database. Also, since there were two Geologic Units fields (geologic units and geologic units 1), I appended the info in geologic units 1 into the online database.
